### ISSUE TITLE
Windows環境での動作

### ISSUE THREAD

**Issue by bleu48** [murosan/shogi-board#29]
Windows環境での動作を確認しました。
多くのエンジンが自ファイルに対する相対パスで評価関数などを置いています。
遠いパスから絶対パスで起動されると認識できないようです。

絶対パスで規定した自作エンジンでは問題なく動作していますので
エンジン起動時にWindowsのカレントを実行ファイルがあるパスにすれば多くのエンジンで動作すると思います。

**Comment by murosan** [comment]
指摘ありがとうございます。近いうちに対応します :bow:

**Comment by murosan** [comment]
https://github.com/murosan/shogi-board-server/releases/tag/v1.3.0
バージョン 1.3.0 にて、修正しました。
報告ありがとうございました！
