### ISSUE TITLE
shogi-board-serverはlocalhost内でしか立てられませんか？

### ISSUE THREAD

**Issue by Kei-Toba** [murosan/shogi-board#31]
初歩的な質問で申し訳ありません。
Macで立てたshogi-board-serverを利用してスマホのブラウザから将棋エンジンを使いたいのですが、shogi-board-serverをlocalhost外から利用できる方法はありますか？

**Comment by murosan** [comment]
同一LAN内であれば、プライベートIPへアクセスすることで可能と思います。

ただ、UIがスマホ用ではないため、操作がなかなか大変かなと思います。
